local category_name = "animatorio-animation-validation"
local item_name = "animatorio-animation-validation-token"
local recipe_name = "animatorio-animation-validation"

data:extend({
  {type = "recipe-category", name = category_name},
  {
    type = "item",
    name = item_name,
    icon = "__core__/graphics/empty.png",
    icon_size = 1,
    stack_size = 1,
    hidden = true,
  },
  {
    type = "recipe",
    name = recipe_name,
    category = category_name,
    enabled = true,
    hidden = true,
    energy_required = 100000,
    ingredients = {},
    results = {{type = "item", name = item_name, amount = 1}},
  },
})

-- Apply validation recipe to all assembling machines that have an animatorio
-- animation defined (discovered via generated asset names). Falls back to
-- patching all assembling machines if no generated list is present, so new
-- assets don't require editing this file.
local known_assets = {}
do
  local ok, assets = pcall(function()
    -- generated by sync step; optional
    return require("generated-asset-names")
  end)
  if ok and type(assets) == "table" then
    for _, name in ipairs(assets) do known_assets[name] = true end
  end
end

local function is_known(name)
  if next(known_assets) == nil then return true end
  return known_assets[name] ~= nil
end

for name, prototype in pairs(data.raw["assembling-machine"] or {}) do
  if is_known(name) then
    prototype.surface_conditions = nil
    prototype.energy_source = {type = "void"}
    prototype.energy_usage = "1W"
    prototype.fixed_recipe = nil
    prototype.crafting_categories = {category_name}
  end
end

for name, prototype in pairs(data.raw["container"] or {}) do
  if is_known(name) then prototype.surface_conditions = nil end
end
